### ISSUE TITLE
ERROR:app.services.llm_service:Error generating response: 1 validation error for StrArrayResponseModel

### ISSUE THREAD

**Issue by wangruidedie** [whyhow-ai/knowledge-table#59]
## Describe the bug

LLM returned the result correctly, but the error is as follows. Is it because the model did not generate output in the correct format?

INFO:httpx:HTTP Request: POST http://localhost:8000/v1/chat/completions "HTTP/1.1 200 OK"
ERROR:app.services.llm_service:Error generating response: 1 validation error for StrArrayResponseModel
  Input should be an object [type=model_type, input_value=['糖尿病', '肥胖', '...病', '心血管疾病'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.9/v/model_type
Traceback (most recent call last):
  File "/CSTemp/zk/knowledge-table/backend/src/app/services/llm_service.py", line 143, in generate_response
    response = await llm_service.generate_completion(prompt, output_model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/CSTemp/zk/knowledge-table/backend/src/app/services/llm/openai_llm_service.py", line 45, in generate_completion
    response = self.client.beta.chat.completions.parse(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/CSTemp/fishfield/Anaconda3/envs/knowledgeTable/lib/python3.11/site-packages/openai/resources/beta/chat/completions.py", line 154, in parse
    return self._post(
           ^^^^^^^^^^^
  File "/CSTemp/fishfield/Anaconda3/envs/knowledgeTable/lib/python3.11/site-packages/openai/_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/CSTemp/fishfield/Anaconda3/envs/knowledgeTable/lib/python3.11/site-packages/openai/_base_client.py", line 954, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/CSTemp/fishfield/Anaconda3/envs/knowledgeTable/lib/python3.11/site-packages/openai/_base_client.py", line 1060, in _request
    return self._process_response(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/CSTemp/fishfield/Anaconda3/envs/knowledgeTable/lib/python3.11/site-packages/openai/_base_client.py", line 1159, in _process_response
    return api_response.parse()
           ^^^^^^^^^^^^^^^^^^^^
  File "/CSTemp/fishfield/Anaconda3/envs/knowledgeTable/lib/python3.11/site-packages/openai/_response.py", line 319, in parse
    parsed = self._options.post_parser(parsed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/CSTemp/fishfield/Anaconda3/envs/knowledgeTable/lib/python3.11/site-packages/openai/resources/beta/chat/completions.py", line 148, in parser
    return _parse_chat_completion(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/CSTemp/fishfield/Anaconda3/envs/knowledgeTable/lib/python3.11/site-packages/openai/lib/_parsing/_completions.py", line 110, in parse_chat_completion
    "parsed": maybe_parse_content(
              ^^^^^^^^^^^^^^^^^^^^
  File "/CSTemp/fishfield/Anaconda3/envs/knowledgeTable/lib/python3.11/site-packages/openai/lib/_parsing/_completions.py", line 161, in maybe_parse_content
    return _parse_content(response_format, message.content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/CSTemp/fishfield/Anaconda3/envs/knowledgeTable/lib/python3.11/site-packages/openai/lib/_parsing/_completions.py", line 221, in _parse_content
    return cast(ResponseFormatT, model_parse_json(response_format, content))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/CSTemp/fishfield/Anaconda3/envs/knowledgeTable/lib/python3.11/site-packages/openai/_compat.py", line 166, in model_parse_json
    return model.model_validate_json(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/CSTemp/fishfield/Anaconda3/envs/knowledgeTable/lib/python3.11/site-packages/pydantic/main.py", line 625, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for StrArrayResponseModel
  Input should be an object [type=model_type, input_value=['糖尿病', '肥胖', '...病', '心血管疾病'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.9/v/model_type
INFO:     10.233.70.0:39777 - "POST /api/v1/query HTTP/1.1" 200 OK

## Screenshots
<img width="638" alt="image" src="https://github.com/user-attachments/assets/b979e8e6-2f82-4b5e-812c-01a33e6a7313">

**Comment by recchris** [comment]
Thanks @wangruidedie, taking a look.

**Comment by recchris** [comment]
@wangruidedie can you clarify how I can replicate this issue? The error seems to indicate that the input format is incorrect. This would lead me to believe that the output from the LLM is incorrectly formatted, however, I'm unable to replicate the issue on my side.

- The output format is "list of text," correct?
- What kind of documents did you upload? Are you able to share or describe so I can replicate on my side?
- Is this happening repeatedly or was this a one-off issue? Are you seeing this with other questions/formats/documents as well?

**Comment by wangruidedie** [comment]
Yes, the output format is "list of text," .I uploaded a pdf document about medicine and I asked the question which diseases are mentioned in this document. No matter what question I ask, I get the same type of error.It may be that the LLM I use can't  output the result with correct format.

**Comment by recchris** [comment]
> Yes, the output format is "list of text," .I uploaded a pdf document about medicine and I asked the question which diseases are mentioned in this document. No matter what question I ask, I get the same type of error.It may be that the LLM I use can't  output the result with correct format.

Got it. Which LLM are you using? Did you write a new service for that LLM? Are you able to share a link to a fork where you've done this?

**Comment by wangruidedie** [comment]
The llm I'm using is qwen2.5-14b-instruct, which is an open source model on Huggingface. I use vllm to deploy it to my local.

**Comment by recchris** [comment]
> The llm I'm using is qwen2.5-14b-instruct, which is an open source model on Huggingface. I use vllm to deploy it to my local.

Got it. You probably need to tweak the prompt to ensure the output conforms to the format that the pydantic model is expecting. Sometimes, passing the pydantic model into the prompt is sufficient, but you may need to experiment a bit. We are using OpenAI structured outputs to pass in a pydantic response model, see [here](https://github.com/whyhow-ai/knowledge-table/blob/main/backend/src/app/services/llm/openai_llm_service.py#L41).

Feel free to share your fork and we can try to make some suggestions.

**Comment by wangruidedie** [comment]
Thanks, I'm going to try to do this as you mentioned

**Comment by recchris** [comment]
Checking in, how's it going @wangruidedie?

**Comment by viegoxu01** [comment]
> Thanks, I'm going to try to do this as you mentioned

I'm facing the same problem now, have you fixed this issue bro

**Comment by WR-CREATOR** [comment]
I also face the same problem. It seems that only OpenAI's LLM can be used. Other models do not support structured output, which will cause verification errors.

**Comment by lwing1966** [comment]
> I also face the same problem. It seems that only OpenAI's LLM can be used. Other models do not support structured output, which will cause verification errors.

when you use local llm，you can use this prompt “the response must be this json format：{"answer"：［"str1","str2"］}”,in end of the question。

then is OK。
